# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'asbappios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAD
pod ‘lottie-ios’
pod 'SnapKit', '~> 4.0.0'
pod ‘ViewAnimator’
pod ‘Popover’
pod 'GoogleSignIn'
pod 'FSCalendar'
pod 'GoogleAPIClient'
pod 'GTMOAuth2'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
end
